version: "3.9"

services:
  app:
    container_name: nolate-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5522:8080"
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: optional:file:/config/env.properties
      LOGGING_FILE_NAME: /logs/app.log
    volumes:
      - ./src/main/resources/env.properties:/config/env.properties:ro
      - ./logs:/logs
    extra_hosts:
      - "host.docker.internal:host-gateway"