FROM eclipse-temurin:21-jdk AS build
WORKDIR /workspace

COPY . .

RUN chmod +x ./gradlew

RUN ./gradlew clean bootWar -x test

RUN WAR_FILE=$(find build/libs -name "*.war" ! -name "*plain*" | head -n 1) && \
    cp "$WAR_FILE" /workspace/app.war

FROM eclipse-temurin:21-jre
WORKDIR /app

COPY --from=build /workspace/app.war /app/app.war

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app/app.war"]