version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: late_project_mysql
    restart: unless-stopped
    ports:
      - "33061:3306"
    env_file:
      - ./docker/mysql/.env
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: